- name: Ensure Active Directory tools directory exists
  ansible.builtin.file:
    path: /opt/tools/ad
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Install BloodHound
  ansible.builtin.apt:
    name: bloodhound
    state: present

- name: Install CrackMapExec
  ansible.builtin.git:
    repo: 'https://github.com/Porchetta-Industries/CrackMapExec.git'
    dest: /opt/tools/ad/CrackMapExec
    version: master
    force: yes

- name: Install CrackMapExec dependencies
  ansible.builtin.pip:
    name:
      - impacket
      - flask
      - pylnk3
      - setuptools
      - wheel
      - cffi
      - python-dev

- name: Install Impacket
  ansible.builtin.git:
    repo: 'https://github.com/fortra/impacket.git'
    dest: /opt/tools/ad/impacket
    version: master
    force: yes

- name: Install Impacket dependencies
  ansible.builtin.shell: |
    cd /opt/tools/ad/impacket
    python3 -m pip install -r requirements.txt
    python3 setup.py install

- name: Install Certipy
  ansible.builtin.git:
    repo: 'https://github.com/ly4k/Certipy.git'
    dest: /opt/tools/ad/Certipy
    version: master
    force: yes

- name: Install Certipy dependencies
  ansible.builtin.pip:
    name:
      - cryptography
      - requests
      - ldap3
      - impacket

- name: Install ntlmrelayx from Impacket
  ansible.builtin.file:
    src: /opt/tools/ad/impacket/examples/ntlmrelayx.py
    dest: /usr/local/bin/ntlmrelayx
    state: link
    mode: '0755'

- name: Install secretsdump from Impacket
  ansible.builtin.file:
    src: /opt/tools/ad/impacket/examples/secretsdump.py
    dest: /usr/local/bin/secretsdump
    state: link
    mode: '0755'

- name: Install Rubeus
  ansible.builtin.get_url:
    url: "https://github.com/GhostPack/Rubeus/releases/latest/download/Rubeus.exe"
    dest: /opt/tools/ad/Rubeus.exe
    mode: '0755'

- name: Install SharpHound
  ansible.builtin.get_url:
    url: "https://github.com/BloodHoundAD/BloodHound/blob/master/Collectors/SharpHound.exe?raw=true"
    dest: /opt/tools/ad/SharpHound.exe
    mode: '0755'
