- name: Ensure base tools directory exists
  ansible.builtin.file:
    path: /opt/tools
    state: directory
    owner: "{{ ansible_env.USER | default('root') }}"
    group: "{{ ansible_env.USER | default('root') }}"
    mode: '0755'
  become: true

- name: Include tool installation tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - apt-config.yml
    - vscode.yml
    - web.yml
    - dirsearch.yml
    - git-dumper.yml
    - ad.yml
    - brute-forcing.yml
    - bloodhound.yml
    # - recon.yml
    #- shells.yml
    #- privilege_escalation.yml
    #- networking.yml
    #- post_exploitation.yml
    #- blue_team.yml
    #- bug_bounty.yml
  loop_control:
    label: "{{ item }}"
  when: item is not none
