- name: Ensure Post Exploitation tools directory exists
  ansible.builtin.file:
    path: /opt/tools/post_exploitation
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Install Mimikatz (Windows Credential Dumping)
  ansible.builtin.git:
    repo: 'https://github.com/gentilkiwi/mimikatz.git'
    dest: /opt/tools/post_exploitation/mimikatz
    version: master
    force: yes

- name: Install LaZagne (Credential Recovery)
  ansible.builtin.git:
    repo: 'https://github.com/AlessandroZ/LaZagne.git'
    dest: /opt/tools/post_exploitation/lazagne
    version: master
    force: yes

- name: Install PowerSploit (Post-Exploitation Framework)
  ansible.builtin.git:
    repo: 'https://github.com/PowerShellMafia/PowerSploit.git'
    dest: /opt/tools/post_exploitation/PowerSploit
    version: master
    force: yes

- name: Install Pupy (Cross-platform RAT)
  ansible.builtin.git:
    repo: 'https://github.com/n1nj4sec/pupy.git'
    dest: /opt/tools/post_exploitation/pupy
    version: master
    force: yes

- name: Install Empire (Post-Exploitation Framework)
  ansible.builtin.git:
    repo: 'https://github.com/BC-SECURITY/Empire.git'
    dest: /opt/tools/post_exploitation/Empire
    version: master
    force: yes
