- name: Ensure system applications directory exists
  ansible.builtin.file:
    path: /opt/apps
    state: directory
    owner: "{{ ansible_env.USER | default('root') }}"
    group: "{{ ansible_env.USER | default('root') }}"
    mode: '0755'
  become: true

- name: Check if VSCode is installed
  ansible.builtin.command: dpkg-query -W -f='${Version}' code
  register: vscode_installed_version
  ignore_errors: true
  changed_when: false

- name: Get latest VSCode version from GitHub releases
  ansible.builtin.uri:
    url: "https://api.github.com/repos/microsoft/vscode/releases/latest"
    return_content: yes
  register: vscode_latest_release
  when: vscode_installed_version.stdout | default('none') == 'none'

- name: Extract latest version from GitHub API
  ansible.builtin.set_fact:
    vscode_latest: "{{ vscode_latest_release.json.tag_name | regex_replace('^v', '') }}"
  when: vscode_installed_version.stdout | default('none') == 'none'

- name: Download latest VSCode for ARM64 if not installed
  ansible.builtin.get_url:
    url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64"
    dest: /opt/apps/vscode-arm64.deb
    mode: '0644'
  when: vscode_installed_version.stdout | default('none') == 'none'
  become: true

- name: Install VSCode for ARM64
  ansible.builtin.apt:
    deb: /opt/apps/vscode-arm64.deb
  when: vscode_installed_version.stdout | default('none') == 'none'
  become: true

- name: Ensure VSCode extensions directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_env.USER }}/.vscode/extensions"
    state: directory
    owner: "{{ ansible_env.USER | default('root') }}"
    group: "{{ ansible_env.USER | default('root') }}"
    mode: '0755'

- name: Install recommended VSCode extensions (including Java Decompiler)
  ansible.builtin.command: >
    code --install-extension {{ item }} --force
  loop:
    - ms-python.python
    - ms-vscode.cpptools
    - redhat.vscode-yaml
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.remote-ssh
    - eamodio.gitlens
    - dgileadi.java-decompiler  # ✅ Java Decompiler for .jar files
  changed_when: false
  become_user: "{{ ansible_env.USER | default('root') }}"
