- name: Include tool installation tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    #- recon.yml
    #- web.yml
    #- ad.yml
    #- shells.yml
    #- privilege_escalation.yml
    #- networking.yml
    #- post_exploitation.yml
    #- blue_team.yml
    #- bug_bounty.yml
    #-wordlists
