- name: Ensure fuzzing wordlists directory exists
  ansible.builtin.file:
    path: /opt/wordlists/fuzzing
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  become: true  # Ensures directory is created with root privileges

- name: Check if fuzz.txt exists
  ansible.builtin.stat:
    path: /opt/wordlists/fuzzing/fuzz.txt
  register: fuzz_wordlist

- name: Download fuzzing wordlist if not already present
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/Bo0oM/fuzz.txt/master/fuzz.txt"
    dest: /opt/wordlists/fuzzing/fuzz.txt
    mode: '0644'
  when: not fuzz_wordlist.stat.exists

- name: Clone RobotsDisallowed wordlists if not already present
  ansible.builtin.git:
    repo: 'https://github.com/danielmiessler/RobotsDisallowed.git'
    dest: /opt/wordlists/fuzzing/robots_disallowed
    version: master
    force: yes
