- name: Ensure wordlists directory exists
  ansible.builtin.file:
    path: /opt/wordlists/seclists
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Clone SecLists repository
  ansible.builtin.git:
    repo: 'https://github.com/danielmiessler/SecLists.git'
    dest: /opt/wordlists/seclists
    version: master
    force: yes
