- name: Ensure SecLists directory exists
  ansible.builtin.file:
    path: /opt/wordlists/seclists
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  become: true  # Ensures directory is created with root privileges

- name: Clone SecLists repository if not already present
  ansible.builtin.git:
    repo: 'https://github.com/danielmiessler/SecLists.git'
    dest: /opt/wordlists/seclists
    version: master
    force: yes
