- name: Install system dependencies
  become: yes
  apt:
    name:
      - build-essential
      - cmake
      - meson
      - ninja-build
      - pkg-config
      - python3
      - python3-pip
      - curl
      - wget
      - unzip
      - lxappearance
      - dconf-cli
    state: present
    update_cache: yes
