- name: Ensure wallpaper directory exists
  file:
    path: "~/.wallpaper"
    state: directory
    mode: '0755'

- name: Copy wallpaper to system location
  copy:
    src: "files/wallpapers/kali.jpg"
    dest: "~/.wallpaper/kali.jpg"
    mode: '0644'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Set desktop background using feh
  command: "feh --bg-scale {{ background_image }}"

- name: Ensure feh sets background on startup
  lineinfile:
    path: "~/.config/i3/config"
    line: "exec --no-startup-id feh --bg-scale {{ background_image }}"
    create: yes
