- name: Setup Kali Linux with i3
  hosts: localhost
  vars_files:
    - ../group_vars/all.yml  # ✅ Explicitly load variables
  roles:
    - i3
    - configure-system
    - wordlists
    - install-tools
    #- customize-browser
